
// bulk_update_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type BulkUpdateResponse struct {
    CreatedRecords []string `json:"createdRecords"`
    UpdatedRecords []string `json:"updatedRecords"`
    Records []Record `json:"records"`
}
