
// bulk_update_request automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type BulkUpdateRequest struct {
    PerformUpsert []string `json:"performUpsert"`
    ReturnFieldsByFieldId bool `json:"returnFieldsByFieldId"`
    Typecast bool `json:"typecast"`
    Records []Record `json:"records"`
}

