
// Client automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    
    
    "github.com/apioo/sdkgen-go"
    
    
    
    
)

type Client struct {
    internal *sdkgen.ClientAbstract
}

func (client *Client) Meta() *MetaTag {
    return NewMetaTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Records() *RecordsTag {
    return NewRecordsTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Fields() *FieldsTag {
    return NewFieldsTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Table() *TableTag {
    return NewTableTag(client.internal.HttpClient, client.internal.Parser)
}




func NewClient(baseUrl string, credentials sdkgen.CredentialsInterface) (*Client, error) {
	var client, err = sdkgen.NewClient(baseUrl, credentials)
    if err != nil {
        return &Client{}, err
    }

	return &Client{
		internal: client,
	}, nil
}

func Build(token string) (*Client, error) {
    var credentials = sdkgen.HttpBearer{Token: token}

    return NewClient("https://api.airtable.com/", credentials)
}

