
// CommentsTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    "bytes"
    "encoding/json"
    "errors"
    "fmt"
    
    "io"
    "net/http"
    "net/url"
    
)

type CommentsTag struct {
    internal *sdkgen.TagAbstract
}



// GetAll Returns a list of comments for the record from newest to oldest.
func (client *CommentsTag) GetAll(baseId string, tableIdOrName string, recordId string) (CommentCollection, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableIdOrName"] = tableIdOrName
    pathParams["recordId"] = recordId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/:baseId/:tableIdOrName/:recordId/comments", pathParams))
    if err != nil {
        return CommentCollection{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return CommentCollection{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return CommentCollection{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return CommentCollection{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data CommentCollection
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return CommentCollection{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 403 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return CommentCollection{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return CommentCollection{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return CommentCollection{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return CommentCollection{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Create Creates a comment on a record. User mentioned is supported.
func (client *CommentsTag) Create(baseId string, tableIdOrName string, recordId string, payload Comment) (Comment, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableIdOrName"] = tableIdOrName
    pathParams["recordId"] = recordId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/:baseId/:tableIdOrName/:recordId/comments", pathParams))
    if err != nil {
        return Comment{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return Comment{}, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("POST", u.String(), reqBody)
    if err != nil {
        return Comment{}, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Comment{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Comment{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Comment
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Comment{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 403 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Comment{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Comment{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Comment{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return Comment{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Update Updates a comment on a record. API users can only update comments they have created. User mentioned is supported.
func (client *CommentsTag) Update(baseId string, tableIdOrName string, recordId string, rowCommentId string, payload Comment) (Comment, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableIdOrName"] = tableIdOrName
    pathParams["recordId"] = recordId
    pathParams["rowCommentId"] = rowCommentId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/:baseId/:tableIdOrName/:recordId/comments/:rowCommentId", pathParams))
    if err != nil {
        return Comment{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return Comment{}, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("PATCH", u.String(), reqBody)
    if err != nil {
        return Comment{}, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Comment{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Comment{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Comment
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Comment{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 403 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Comment{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Comment{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Comment{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return Comment{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Delete Deletes a comment from a record. Non-admin API users can only delete comments they have created. Enterprise Admins can delete any comment from a record.
func (client *CommentsTag) Delete(baseId string, tableIdOrName string, recordId string, rowCommentId string) (DeleteResponse, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableIdOrName"] = tableIdOrName
    pathParams["recordId"] = recordId
    pathParams["rowCommentId"] = rowCommentId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/:baseId/:tableIdOrName/:recordId/comments/:rowCommentId", pathParams))
    if err != nil {
        return DeleteResponse{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("DELETE", u.String(), nil)
    if err != nil {
        return DeleteResponse{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return DeleteResponse{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return DeleteResponse{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data DeleteResponse
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return DeleteResponse{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 403 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return DeleteResponse{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return DeleteResponse{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return DeleteResponse{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return DeleteResponse{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}




func NewCommentsTag(httpClient *http.Client, parser *sdkgen.Parser) *CommentsTag {
	return &CommentsTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
