
// comment_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type CommentCollection struct {
    Offset string `json:"offset"`
    Records []Comment `json:"records"`
}
