
// comment_reaction automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type CommentReaction struct {
    Emoji string `json:"emoji"`
    ReactingUser *CommentAuthor `json:"reactingUser"`
}
