
// comment_author automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type CommentAuthor struct {
    Id string `json:"id"`
    Email string `json:"email"`
    Name string `json:"name"`
}
