
// error_details automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type ErrorDetails struct {
    Type string `json:"type"`
    Message string `json:"message"`
}

