
// field automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Field struct {
    Id string `json:"id"`
    Type string `json:"type"`
    Name string `json:"name"`
    Description string `json:"description"`
    Options *FieldOptions `json:"options"`
}

