
// FieldsTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    "bytes"
    "encoding/json"
    "errors"
    "fmt"
    
    "io"
    "net/http"
    "net/url"
    
)

type FieldsTag struct {
    internal *sdkgen.TagAbstract
}



// Create Creates a new column and returns the schema for the newly created column.
func (client *FieldsTag) Create(baseId string, tableId string, payload Field) (Field, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableId"] = tableId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/meta/bases/:baseId/tables/:tableId/fields", pathParams))
    if err != nil {
        return Field{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return Field{}, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("POST", u.String(), reqBody)
    if err != nil {
        return Field{}, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Field{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Field{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Field
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Field{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 403 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Field{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Field{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Field{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return Field{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Update Updates the name and/or description of a field. At least one of name or description must be specified.
func (client *FieldsTag) Update(baseId string, tableId string, columnId string, payload Field) (Field, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableId"] = tableId
    pathParams["columnId"] = columnId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/meta/bases/:baseId/tables/:tableId/fields/:columnId", pathParams))
    if err != nil {
        return Field{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return Field{}, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("PATCH", u.String(), reqBody)
    if err != nil {
        return Field{}, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Field{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Field{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Field
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Field{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 403 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Field{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Field{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Field{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return Field{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}




func NewFieldsTag(httpClient *http.Client, parser *sdkgen.Parser) *FieldsTag {
	return &FieldsTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
