
// MetaTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    "encoding/json"
    "errors"
    "github.com/apioo/sdkgen-go"
    "io"
    "net/http"
    "net/url"
    
)

type MetaTag struct {
    internal *sdkgen.TagAbstract
}



// GetWhoami Retrieve the user&#039;s ID. For OAuth access tokens, the scopes associated with the token used are also returned.
func (client *MetaTag) GetWhoami() (User, error) {
    pathParams := make(map[string]interface{})

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/meta/whoami", pathParams))
    if err != nil {
        return User{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return User{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return User{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return User{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response User
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return User{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        default:
            return User{}, errors.New("the server returned an unknown status code")
    }
}



func NewMetaTag(httpClient *http.Client, parser *sdkgen.Parser) *MetaTag {
	return &MetaTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
