
// record automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Record struct {
    Id string `json:"id"`
    CreatedTime string `json:"createdTime"`
    Fields map[string]any `json:"fields"`
}
