
// RecordsTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    "bytes"
    "encoding/json"
    "errors"
    "fmt"
    
    "io"
    "net/http"
    "net/url"
    
)

type RecordsTag struct {
    internal *sdkgen.TagAbstract
}



// GetAll List records in a table. Note that table names and table ids can be used interchangeably. We recommend using table IDs so you don&#039;t need to modify your API request when your table name changes.
func (client *RecordsTag) GetAll(baseId string, tableIdOrName string, timeZone string, userLocale string, pageSize int, maxRecords int, offset string, view string, sort string, filterByFormula string, cellFormat string, fields string, returnFieldsByFieldId bool, recordMetadata string) (RecordCollection, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableIdOrName"] = tableIdOrName

    queryParams := make(map[string]interface{})
    queryParams["timeZone"] = timeZone
    queryParams["userLocale"] = userLocale
    queryParams["pageSize"] = pageSize
    queryParams["maxRecords"] = maxRecords
    queryParams["offset"] = offset
    queryParams["view"] = view
    queryParams["sort"] = sort
    queryParams["filterByFormula"] = filterByFormula
    queryParams["cellFormat"] = cellFormat
    queryParams["fields"] = fields
    queryParams["returnFieldsByFieldId"] = returnFieldsByFieldId
    queryParams["recordMetadata"] = recordMetadata

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/:baseId/:tableIdOrName", pathParams))
    if err != nil {
        return RecordCollection{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return RecordCollection{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return RecordCollection{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return RecordCollection{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data RecordCollection
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return RecordCollection{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 403 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return RecordCollection{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return RecordCollection{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return RecordCollection{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return RecordCollection{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Get Retrieve a single record. Any &quot;empty&quot; fields (e.g. &quot;&quot;, [], or false) in the record will not be returned.
func (client *RecordsTag) Get(baseId string, tableIdOrName string, recordId string) (Record, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableIdOrName"] = tableIdOrName
    pathParams["recordId"] = recordId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/:baseId/:tableIdOrName/:recordId", pathParams))
    if err != nil {
        return Record{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return Record{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Record{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Record{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Record
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Record{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 403 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Record{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Record{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Record{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return Record{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Create Creates multiple records. Note that table names and table ids can be used interchangeably. We recommend using table IDs so you don&#039;t need to modify your API request when your table name changes.
func (client *RecordsTag) Create(baseId string, tableIdOrName string, payload RecordCollection) (RecordCollection, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableIdOrName"] = tableIdOrName

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/:baseId/:tableIdOrName", pathParams))
    if err != nil {
        return RecordCollection{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return RecordCollection{}, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("POST", u.String(), reqBody)
    if err != nil {
        return RecordCollection{}, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return RecordCollection{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return RecordCollection{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data RecordCollection
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return RecordCollection{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 403 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return RecordCollection{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return RecordCollection{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return RecordCollection{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return RecordCollection{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Replace Updates a single record. Table names and table ids can be used interchangeably. We recommend using table IDs so you don&#039;t need to modify your API request when your table name changes.
func (client *RecordsTag) Replace(baseId string, tableIdOrName string, recordId string, payload Record) (Record, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableIdOrName"] = tableIdOrName
    pathParams["recordId"] = recordId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/:baseId/:tableIdOrName/:recordId", pathParams))
    if err != nil {
        return Record{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return Record{}, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("PUT", u.String(), reqBody)
    if err != nil {
        return Record{}, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Record{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Record{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Record
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Record{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 403 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Record{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Record{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Record{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return Record{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// ReplaceAll Updates up to 10 records, or upserts them when performUpsert is set.
func (client *RecordsTag) ReplaceAll(baseId string, tableIdOrName string, payload BulkUpdateRequest) (BulkUpdateResponse, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableIdOrName"] = tableIdOrName

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/:baseId/:tableIdOrName", pathParams))
    if err != nil {
        return BulkUpdateResponse{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return BulkUpdateResponse{}, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("PUT", u.String(), reqBody)
    if err != nil {
        return BulkUpdateResponse{}, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return BulkUpdateResponse{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return BulkUpdateResponse{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data BulkUpdateResponse
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return BulkUpdateResponse{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 403 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return BulkUpdateResponse{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return BulkUpdateResponse{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return BulkUpdateResponse{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return BulkUpdateResponse{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Update Updates a single record. Table names and table ids can be used interchangeably. We recommend using table IDs so you don&#039;t need to modify your API request when your table name changes.
func (client *RecordsTag) Update(baseId string, tableIdOrName string, recordId string, payload Record) (Record, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableIdOrName"] = tableIdOrName
    pathParams["recordId"] = recordId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/:baseId/:tableIdOrName/:recordId", pathParams))
    if err != nil {
        return Record{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return Record{}, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("PATCH", u.String(), reqBody)
    if err != nil {
        return Record{}, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Record{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Record{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data Record
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Record{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 403 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Record{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Record{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return Record{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return Record{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// UpdateAll Updates up to 10 records, or upserts them when performUpsert is set.
func (client *RecordsTag) UpdateAll(baseId string, tableIdOrName string, payload BulkUpdateRequest) (BulkUpdateResponse, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableIdOrName"] = tableIdOrName

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/:baseId/:tableIdOrName", pathParams))
    if err != nil {
        return BulkUpdateResponse{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return BulkUpdateResponse{}, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("PATCH", u.String(), reqBody)
    if err != nil {
        return BulkUpdateResponse{}, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return BulkUpdateResponse{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return BulkUpdateResponse{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data BulkUpdateResponse
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode == 400 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return BulkUpdateResponse{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 403 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return BulkUpdateResponse{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 404 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return BulkUpdateResponse{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    if statusCode == 500 {
        var data Error
        err := json.Unmarshal(respBody, &data)

        return BulkUpdateResponse{}, &ErrorException{
            Payload: data,
            Previous: err,
        }
    }

    return BulkUpdateResponse{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Delete Deletes a single record
func (client *RecordsTag) Delete(baseId string, tableIdOrName string, recordId string) (DeleteResponse, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableIdOrName"] = tableIdOrName
    pathParams["recordId"] = recordId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/:baseId/:tableIdOrName/:recordId", pathParams))
    if err != nil {
        return DeleteResponse{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("DELETE", u.String(), nil)
    if err != nil {
        return DeleteResponse{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return DeleteResponse{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return DeleteResponse{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data DeleteResponse
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    return DeleteResponse{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}




func NewRecordsTag(httpClient *http.Client, parser *sdkgen.Parser) *RecordsTag {
	return &RecordsTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
