
// record_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type RecordCollection struct {
    Offset string `json:"offset"`
    Records []Record `json:"records"`
}

