
// TableTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    "bytes"
    "encoding/json"
    "errors"
    "github.com/apioo/sdkgen-go"
    "io"
    "net/http"
    "net/url"
    
)

type TableTag struct {
    internal *sdkgen.TagAbstract
}



// Create Creates a new table and returns the schema for the newly created table.
func (client *TableTag) Create(baseId string, payload Table) (Table, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/meta/bases/:baseId/tables", pathParams))
    if err != nil {
        return Table{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return Table{}, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("POST", u.String(), reqBody)
    if err != nil {
        return Table{}, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Table{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Table{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response Table
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return Table{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        default:
            return Table{}, errors.New("the server returned an unknown status code")
    }
}

// Update 
func (client *TableTag) Update(baseId string, tableIdOrName string, payload Table) (Table, error) {
    pathParams := make(map[string]interface{})
    pathParams["baseId"] = baseId
    pathParams["tableIdOrName"] = tableIdOrName

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/v0/meta/bases/:baseId/tables/:tableIdOrName", pathParams))
    if err != nil {
        return Table{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return Table{}, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("PATCH", u.String(), reqBody)
    if err != nil {
        return Table{}, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return Table{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return Table{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response Table
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return Table{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        default:
            return Table{}, errors.New("the server returned an unknown status code")
    }
}



func NewTableTag(httpClient *http.Client, parser *sdkgen.Parser) *TableTag {
	return &TableTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
