
// table automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Table struct {
    Id string `json:"id"`
    PrimaryFieldId string `json:"primaryFieldId"`
    Name string `json:"name"`
    Description string `json:"description"`
    Fields []Field `json:"fields"`
}

